version: '3'

services:
  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - products-service
  
  products-service:
    build: ./products
    restart: on-failure
    ports:
      - "3000:80"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    depends_on:
      - db-service
    
  db-service:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - ./db/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    security_opt:
      - seccomp:unconfined
